name: Mark closed issues as "to release"

on:
  issues:
    types:
      - closed

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        id: get-token
        uses: topmonks/app-auth-action@v1
        with:
          appId: ${{ secrets.PROJECTS_AND_ISSUES_APP_ID }}
          appPrivateKey: ${{ secrets.PROJECTS_AND_ISSUES_APP_PRIVATE_KEY }}
      - name: Move issue to column
        uses: leonsteinhaeuser/project-beta-automations@v2.0.1
        with:
          gh_token: ${{ steps.get-token.outputs.token }}
          organization: topmonks
          project_id: 11
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: ${{ github.event.issue.state_reason == 'not_planned' && 'Done' || 'To Release' }}
      - name: Label issue
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ github.event.issue.state_reason != 'not_planned' }}
        with:
          labels: to-release
